In [1]:
import pandas as pd
import os

In [2]:
# load df 
df = pd.read_csv('above_20_coins.csv')

In [3]:
df.describe()

             price        tirage      amount         year
count   291.000000  2.910000e+02  291.000000   291.000000
mean    121.797732  3.952759e+06    5.309278  2012.422680
std     385.701539  1.766631e+07   10.481867     6.720276
min      20.000000  8.000000e+01    1.000000  1999.000000
25%      26.475000  1.000000e+04    2.000000  2006.000000
50%      37.810000  3.950000e+04    2.000000  2013.000000
75%      60.615000  8.500000e+04    2.000000  2018.000000
max    4179.000000  1.213829e+08   50.000000  2023.000000

In [4]:
df["coin_name"]

0               Andorre-1-Euro-2020
1               Andorre-1-Euro-2019
2               Andorre-2-Euro-2016
3               Andorre-1-Cent-2014
4              Autriche-1-Euro-2015
                   ...
286    Vatican-2-Euro-commemorative
287     Malte-2-Euro-Commemoratives
288          Luxembourg-2-Euro-100e
289           Luxembourg-2-Euro-40e
290    Vatican-2-Euro-commemorative
Name: coin_name, Length: 291, dtype: object

In [5]:
# function to count how many pictures in a folder
def count_pictures_in_folder(folder_path: str) -> int:
    count = 0
    for file in os.listdir(folder_path):
        if file.endswith(".webp"):
            count += 1
    return count
    # function to count how many folders in a directory
def count_folders_in_directory(directory_path: str) -> int:
    count = 0
    for file in os.listdir(directory_path):
        if os.path.isdir(os.path.join(directory_path, file)):
            count += 1
    return count

count_pictures_in_folder("/workspaces/AICoinXpert/algo/webscraping/data/selected_coins_above20")

193

In [6]:
df.folder_path

0        Andorre-1-Euro-2020-3291750-160940548933833.jpg
1        Andorre-1-Euro-2019-3250000-157568996679098.jpg
2        Andorre-2-Euro-2016-3141550-150537845823247.jpg
3        Andorre-1-Cent-2014-3028970-146428257035657.jpg
4       Autriche-1-Euro-2015-3022890-155496795756469.jpg
                             ...
286    Vatican-2-Euro-commemorative-2017-Centenaire-d...
287    Malte-2-Euro-Commemoratives-Serie-2016-2020-De...
288    Luxembourg-2-Euro-100e-anniversaire-de-la-nais...
289    Luxembourg-2-Euro-40e-anniversaire-du-mariage-...
290    Vatican-2-Euro-commemorative-2007-80e-annivers...
Name: folder_path, Length: 291, dtype: object

In [7]:
import os

def get_folder_names(path):
    """
    Get all the names of the folders and files in a directory.

    Args:
        path (str): The path of the directory.

    Returns:
        list: A list containing the names of the folders and files.
    """
    return [name for name in os.listdir(path)]

folder_name = get_folder_names("/workspaces/AICoinXpert/algo/webscraping/data/organized_images_20_above_filtered/train")
len(folder_name)

199

In [8]:
import os
import pandas as pd

def compare_and_update_dataframe(df, directory_path, min_matching_blocks_range=(4, 5)):
    for index, row in df.iterrows():
        folder_path_parts = row['folder_path'].split('-')
        matching_file_path = None
        
        common_parts = set()  # Initialize the common parts to an empty set
        
        for file_name in os.listdir(directory_path):
            if file_name.endswith('.webp'):
                file_name_parts = file_name.split('-')
                common_parts = set(folder_path_parts) & set(file_name_parts)
            
            if len(common_parts) in range(min_matching_blocks_range[0], min_matching_blocks_range[1]+1):
                matching_file_path = os.path.join(directory_path, file_name)
                break
        
        if matching_file_path:
            df.at[index, 'matching_file_path'] = matching_file_path
        else:
            df.at[index, 'matching_file_path'] = None
    
    return df

directory_path = '/workspaces/AICoinXpert/algo/webscraping/data/selected_coins_above20'

df = compare_and_update_dataframe(df, directory_path)
df

,folder_path,price,tirage,country,currency,amount,year,coin_name,commemorative,matching_file_path
0,Andorre-1-Euro-2020-3291750-160940548933833.jpg,25.45,12000.0,Andorra,Euro,1,2020,Andorre-1-Euro-2020,False,/workspaces/AICoinXpert/algo/webscraping/data/...
1,Andorre-1-Euro-2019-3250000-157568996679098.jpg,25.83,15000.0,Andorra,Euro,1,2019,Andorre-1-Euro-2019,False,/workspaces/AICoinXpert/algo/webscraping/data/...
2,Andorre-2-Euro-2016-3141550-150537845823247.jpg,29.06,35000.0,Andorra,Euro,2,2016,Andorre-2-Euro-2016,False,/workspaces/AICoinXpert/algo/webscraping/data/...
3,Andorre-1-Cent-2014-3028970-146428257035657.jpg,25.22,200000.0,Andorra,Cent,1,2014,Andorre-1-Cent-2014,False,None
4,Autriche-1-Euro-2015-3022890-155496795756469.jpg,23.72,50000.0,Austria,Euro,1,2015,Autriche-1-Euro-2015,False,/workspaces/AICoinXpert/algo/webscraping/data/...
...,...,...,...,...,...,...,...,...,...,...
286,Vatican-2-Euro-commemorative-2017-Centenaire-d...,166.00,10000.0,Vatican,Euro,2,2017,Vatican-2-Euro-commemorative,True,/workspaces/AICoinXpert/algo/webscraping/data/...
287,Malte-2-Euro-Commemoratives-Serie-2016-2020-De...,165.00,500.0,Malta,Euro,2,2016,Malte-2-Euro-Commemoratives,True,/workspaces/AICoinXpert/algo/webscraping/data/...
288,Luxembourg-2-Euro-100e-anniversaire-de-la-nais...,159.00,2500.0,Luxembourg,Euro,2,2021,Luxembourg-2-Euro-100e,True,/workspaces/AICoinXpert/algo/webscraping/data/...
289,Luxembourg-2-Euro-40e-anniversaire-du-mariage-...,157.00,2500.0,Luxembourg,Euro,2,2021,Luxembourg-2-Euro-40e,True,/workspaces/AICoinXpert/algo/webscraping/data/...
290,Vatican-2-Euro-commemorative-2007-80e-annivers...,151.00,85000.0,Vatican,Euro,2,2007,Vatican-2-Euro-commemorative,True,/workspaces/AICoinXpert/algo/webscraping/data/...

In [9]:
# check the nan in a column and count them

df['matching_file_path'].isna().sum()

71

In [13]:
# remove the nan row
df = df.dropna()

In [10]:
# remove columns 

df = df.drop(columns=['folder_path', 'commemorative'])

In [11]:
# rename columns 
df.rename(columns={'matching_file_path':'folder_path'}, inplace=True)

In [12]:
order = ['folder_path', 'price', 'tirage', 'currency', 'amount', 'year', 'coin_name']
df = df.reindex(columns=order)

In [13]:
df["folder_path"] = df["folder_path"].str.replace("/workspaces/AICoinXpert/algo/webscraping/data/selected_coins_above20/", '')

In [14]:
df

,folder_path,price,tirage,currency,amount,year,coin_name
0,Andorre-1-Euro-2020-3291750-160940548933833.webp,25.45,12000.0,Euro,1,2020,Andorre-1-Euro-2020
1,Andorre-1-Euro-2019-3250000-157568996679098.webp,25.83,15000.0,Euro,1,2019,Andorre-1-Euro-2019
2,Andorre-2-Euro-2016-3141550-155487582282142.webp,29.06,35000.0,Euro,2,2016,Andorre-2-Euro-2016
3,None,25.22,200000.0,Cent,1,2014,Andorre-1-Cent-2014
4,Autriche-1-Euro-2015-3022890-155496795756469.webp,23.72,50000.0,Euro,1,2015,Autriche-1-Euro-2015
...,...,...,...,...,...,...,...
286,Monaco-2-Euro-10e-anniversaire-de-mariage-du-P...,166.00,10000.0,Euro,2,2017,Vatican-2-Euro-commemorative
287,Malte-2-Euro-2022-3355400-167298744395742.webp,165.00,500.0,Euro,2,2016,Malte-2-Euro-Commemoratives
288,France-2-Euro-commemorative-2015-225-ans-de-la...,159.00,2500.0,Euro,2,2021,Luxembourg-2-Euro-100e
289,France-2-Euro-commemorative-2015-225-ans-de-la...,157.00,2500.0,Euro,2,2021,Luxembourg-2-Euro-40e
290,Monaco-2-Euro-10e-anniversaire-de-mariage-du-P...,151.00,85000.0,Euro,2,2007,Vatican-2-Euro-commemorative

In [15]:
#df.to_csv("data_for_db.csv", index=False)

In [16]:
#### Open clean Dataframe

df_before_post = pd.read_csv('/workspaces/AICoinXpert/algo/webscraping/coins_to_db.csv', index_col=False)

In [18]:
# function to get the average tirage of coins values per country
def fill_tirage_with_average(df):
    df['tirage'] = pd.to_numeric(df['tirage'], errors='coerce').astype(float)  # Convert 'tirage' column to float and handle NaN values
    
    for country in df['country'].unique():
        mean_tirage = df[df['country'] == country]['tirage'].mean()
        df.loc[(df['country'] == country) & (df['tirage'].isnull()), 'tirage'] = mean_tirage
        
    return df

df_before_post = fill_tirage_with_average(df_before_post)

,folder_path,price,tirage,country,currency,amount,year,coin_name
0,Allemagne-1-Cent-2022-A-3348000-16493877409827...,1.74,4.597929e+07,Germany,Cent,1,2022,Allemagne-1-Cent-2022
1,Allemagne-2-Cent-2022-A-3348050-16493877464115...,2.51,4.220000e+07,Germany,Cent,2,2022,Allemagne-2-Cent-2022
2,Allemagne-5-Cent-2022-A-3348100-16493877526415...,2.27,2.700000e+07,Germany,Cent,5,2022,Allemagne-5-Cent-2022
3,Allemagne-10-Cent-2022-A-3348150-1649387757505...,2.61,1.980000e+07,Germany,Cent,10,2022,Allemagne-10-Cent-2022
4,Allemagne-20-Cent-2022-A-3348200-1649387761767...,2.24,2.620000e+07,Germany,Cent,20,2022,Allemagne-20-Cent-2022
...,...,...,...,...,...,...,...,...
3390,Luxembourg-2-Euro-100e-anniversaire-de-la-nais...,159.00,2.500000e+03,Luxembourg,Euro,2,2021,Luxembourg-2-Euro-100e
3391,Luxembourg-2-Euro-40e-anniversaire-du-mariage-...,157.00,2.500000e+03,Luxembourg,Euro,2,2021,Luxembourg-2-Euro-40e
3392,Finlande-2-Euro-commemorative-2017-Nature-finl...,154.00,1.100000e+04,Finland,Euro,2,2017,Finlande-2-Euro-commemorative
3393,Vatican-2-Euro-commemorative-2007-80e-annivers...,151.00,8.500000e+04,Vatican,Euro,2,2007,Vatican-2-Euro-commemorative
3394,Espagne-2-Euro-commemorative-2014-Parc-Gueell-...,148.00,1.200000e+04,Spain,Euro,2,2014,Espagne-2-Euro-commemorative

In [19]:
# check nan values
df_before_post.isnull().sum()

folder_path    0
price          0
tirage         0
country        0
currency       0
amount         0
year           0
coin_name      0
dtype: int64

In [ ]:
df_before_post.to_csv("coins_to_db.csv", index=False)